import QueryProvider from "@/hooks/QueryProvider";
import "./globals.css";
import { Nav } from "@/components/Organisms/nav/Nav";
import { Footer } from "@/components/Templates/Footer/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <QueryProvider>
        <body className="relative font-Nurito">
          <Nav />
          {children}
          <Footer />
        </body>
      </QueryProvider>
    </html>
  );
}
